export const EVENTS_LIST_SELECT = [
    'id',
    'title',
    'description',
    'image_url',
    'start_time',
    'end_time',
    'status',
    'location',
    'meeting_link',
    'recording_url',
    'max_attendees',
    'price',
    'is_members_only',
    'created_by',
    'event_type',
    'target_audience',
    'recording_expires_at',
    'views',
    'category',
    'subcategory',
    'member_price',
    'member_access_type',
    'session_config',
    'specialization_code',
].join(', ')
